version: '3.8'  

services:
  app:
    image: myapp:latest
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "80:80"
    restart: unless-stopped 
    environment:              
      - ENV=production
    volumes:                  
      - app_data:/data

volumes:
  app_data: {}
